export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "04/06/2025",
        BookTime: "1846",
        BookingDate1: "09th April 2025",
        Origin: "CHENNAI",
        Destination: "Canada",
      },
    ],
    Events: [
      {
        EventDate: "05/06/2025",
        EventTime: "0930",
        EventDate1: "5th June 2025",
        EventTime1: "9:30 AM",
        Location: "Chennai",
        Status: "Shipment Connected at Origin Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "05/06/2025",
        EventTime: "1230",
        EventDate1: "5th June 2025",
        EventTime1: "12:30 PM",
        Location: "Chennai",
        Status: "Arrived at Chennai International Airport",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "05/06/2025",
        EventTime: "1530",
        EventDate1: "5th June 2025",
        EventTime1: "3:30 PM",
        Location: "Chennai",
        Status: "Departed from Chennai International Airport",
        FlightCode: "AI104",
        FlightName: "Air India",
      },
      {
        EventDate: "06/06/2025",
        EventTime: "1015",
        EventDate1: "6th June 2025",
        EventTime1: "10:15 AM",
        Location: "Dubai International Airport",
        Status: "Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/06/2025",
        EventTime: "1300",
        EventDate1: "10th June 2025",
        EventTime1: "1:00 PM",
        Location: "Dubai International Airport",
        Status: "Custom Clearance Completed",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "13/06/2025",
        EventTime: "1500",
        EventDate1: "13th June 2025",
        EventTime1: "3:00 PM",
        Location: "Frankfurt International Airport",
        Status: "In Transit via Frankfurt",
        FlightCode: "LH760",
        FlightName: "Lufthansa",
      },
      {
        EventDate: "19/06/2025",
        EventTime: "1100",
        EventDate1: "19th June 2025",
        EventTime1: "11:00 AM",
        Location: "Toronto Pearson International Airport",
        Status: "Arrived at Destination Airport",
        FlightCode: "AC849",
        FlightName: "Air Canada",
      },
      {
        EventDate: "22/06/2025",
        EventTime: "1300",
        EventDate1: "8th June 2025",
        EventTime1: "1:00 PM",
        Location: "Toronto Pearson International Airport",
        Status: "Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "25/06/2025",
        EventTime: "1600",
        EventDate1: "25th June 2025",
        EventTime1: "4:00 PM",
        Location: "Toronto Pearson International Airport",
        Status: "Custom Clearance Completed",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "26/06/2025",
        EventTime: "1630",
        EventDate1: "26th June 2025",
        EventTime1: "4:30 PM",
        Location: "Canada",
        Status: "Shipment Custom Clearance On Hold",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
