export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "19/06/2025",
        BookTime: "1846",
        BookingDate1: "19th June 2025",
        Origin: "CHENNAI",
        Destination: "Canada",
      },
    ],
    Events: [
      {
        EventDate: "30/06/2025",
        EventTime: "1130",
        EventDate1: "30th June 2025",
        EventTime1: "11:30 AM",
        Location: "Natharlands",
        Status: "Shipment On Hold – Awaiting Clearance Documents",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "30/06/2025",
        EventTime: "0830",
        EventDate1: "30th June 2025",
        EventTime1: "8:30 AM",
        Location: "Amsterdam Schiphol Airport",
        Status: "Shipment Undergoing Customs Clearance",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "29/06/2025",
        EventTime: "2145",
        EventDate1: "29th June 2025",
        EventTime1: "9:45 PM",
        Location: "Brussels Airport, Belgium",
        Status: "Shipment Departed to Final Destination",
        FlightCode: "KL1722",
        FlightName: "KLM Royal Dutch Airlines",
      },
      {
        EventDate: "28/06/2025",
        EventTime: "1500",
        EventDate1: "28th June 2025",
        EventTime1: "3:00 PM",
        Location: "Paris Charles de Gaulle, France",
        Status: "Shipment Arrived at Regional Transit Hub",
        FlightCode: "AF887",
        FlightName: "Air France",
      },
      {
        EventDate: "27/06/2025",
        EventTime: "1100",
        EventDate1: "27th June 2025",
        EventTime1: "11:00 AM",
        Location: "Luxembourg Airport",
        Status: "Shipment Departed from Transit Hub",
        FlightCode: "CV731",
        FlightName: "Cargolux",
      },
      {
        EventDate: "24/06/2025",
        EventTime: "1345",
        EventDate1: "24th June 2025",
        EventTime1: "1:45 PM",
        Location: "HYDERABAD AIRPORT",
        Status: "Shipment Departed from Origin",
        FlightCode: "LH753",
        FlightName: "Lufthansa",
      },
      {
        EventDate: "22/06/2025",
        EventTime: "1545",
        EventDate1: "22nd June 2025",
        EventTime1: "3:45 PM",
        Location: "HYDERABAD",
        Status: "Shipment Custom Clearance Completed",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "21/06/2025",
        EventTime: "0930",
        EventDate1: "21st June 2025",
        EventTime1: "9:30 AM",
        Location: "HYDERABAD",
        Status: "Shipment Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "20/06/2025",
        EventTime: "1630",
        EventDate1: "20th June 2025",
        EventTime1: "4:30 PM",
        Location: "HYDERABAD",
        Status: "Shipment Received",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
