export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "09/04/2025",
        BookTime: "1846",
        BookingDate1: "09th April 2025",
        Origin: "CHENNAI",
        Destination: "United Kingdom",
      },
    ],
    Events: [
      {
        EventDate: "13/04/2025",
        EventTime: "0831",
        EventDate1: "13th April 2025",
        EventTime1: "8:31 AM",
        Location: "Poland",
        Status: "Arrived at Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "12/04/2025",
        EventTime: "2106",
        EventDate1: "7th April 2025",
        EventTime1: "12:06 PM",
        Location: "Bengaluru Airport",
        Status: "Departed from Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "12/04/2025",
        EventTime: "1022",
        EventDate1: "12th April 2025",
        EventTime1: "10:22 AM",
        Location: "",
        Status: "We are experiencing transit delays.",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "11/04/2025",
        EventTime: "1610",
        EventDate1: "11th April 2025",
        EventTime1: "4:10 PM",
        Location: "Bengaluru Airport",
        Status: "We are experiencing transit delays.",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "11/04/2025",
        EventTime: "0824",
        EventDate1: "11th April 2025",
        EventTime1: "8:24 AM",
        Location: "",
        Status: "We are experiencing transit delays.",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/04/2025",
        EventTime: "1627",
        EventDate1: "10th April 2025",
        EventTime1: "4:27 PM",
        Location: "Bengaluru Airport",
        Status: "We are experiencing transit delays.",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/04/2025",
        EventTime: "1214",
        EventDate1: "10th April 2025",
        EventTime1: "12:14 PM",
        Location: "Bengaluru Airport",
        Status: "Export Scan",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/04/2025",
        EventTime: "0700",
        EventDate1: "10th April 2025",
        EventTime1: "11:00 AM",
        Location: "Bengaluru Airport",
        Status: "Arrived at Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/04/2025",
        EventTime: "0600",
        EventDate1: "10th April 2025",
        EventTime1: "6:00 AM",
        Location: "Chennai",
        Status: "Departed from Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "9/04/2025",
        EventTime: "2247",
        EventDate1: "9th April 2025",
        EventTime1: "10:47 PM",
        Location: "Chennai",
        Status: "Arrived at Facility",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "9/04/2025",
        EventTime: "1954",
        EventDate1: "9th April 2025",
        EventTime1: "7:54 PM",
        Location: "CHENNAI",
        Status: "SHIPMENT RECEIVED",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "9/04/2025",
        EventTime: "1950",
        EventDate1: "9th April 2025",
        EventTime1: "6:50 PM",
        Location: "CHENNAI",
        Status: "SHIPMENT SENT TO CHENNAI",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "9/04/2025",
        EventTime: "1945",
        EventDate1: "9th April 2025",
        EventTime1: "6:45 PM",
        Location: "",
        Status: "Shipment Manifested Day End Process",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "9/04/2025",
        EventTime: "1822",
        EventDate1: "9th April 2025",
        EventTime1: "6:22 PM",
        Location: "",
        Status:
          "Shipper created a label, UPS has not received the package yet.",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
