export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "04/07/2025",
        BookTime: "1846",
        BookingDate1: "04th July 2025",
        Origin: "CHENNAI",
        Destination: "Australia",
      },
    ],
    Events: [
      {
        EventDate: "13/07/2025",
        EventTime: "1430",
        EventDate1: "10th July 2025",
        EventTime1: "2:30 PM",
        Location: "Sydney Airport",
        Status: "Customs Cleared at Origin",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "10/07/2025",
        EventTime: "0600",
        EventDate1: "10th July 2025",
        EventTime1: "6:00 AM",
        Location: "Sydney Airport",
        Status: "Shipment Arrived at Destination Airport",
        FlightCode: "SQ211",
        FlightName: "Singapore Airlines",
      },
      {
        EventDate: "07/07/2025",
        EventTime: "0400",
        EventDate1: "07th July 2025",
        EventTime1: "4:00 AM",
        Location: "Singapore",
        Status: "Shipment Arrived at Transit Hub",
        FlightCode: "SQ421",
        FlightName: "Singapore Airlines",
      },
      {
        EventDate: "06/07/2025",
        EventTime: "0730",
        EventDate1: "06th July 2025",
        EventTime1: "7:30 AM",
        Location: "Chennai Airport",
        Status: "Shipment Departed from Origin",
        FlightCode: "AI310",
        FlightName: "Air India",
      },
      {
        EventDate: "05/07/2025",
        EventTime: "0930",
        EventDate1: "05th July 2025",
        EventTime1: "9:30 AM",
        Location: "Chennai",
        Status: "Customs Cleared at Origin",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "04/07/2025",
        EventTime: "1630",
        EventDate1: "04th July 2025",
        EventTime1: "4:30 PM",
        Location: "Chennai",
        Status: "Shipment Received at Origin Facility",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
