export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "13/06/2025",
        BookTime: "1846",
        BookingDate1: "13th June 2025",
        Origin: "CHENNAI",
        Destination: "Canada",
      },
    ],
    Events: [
      {
        EventDate: "13/06/2025",
        EventTime: "1630",
        EventDate1: "13th June 2025",
        EventTime1: "4:30 PM",
        Location: "HYDERABAD",
        Status: "SHIPMENT RECEIVED",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "14/06/2025",
        EventTime: "0930",
        EventDate1: "14th June 2025",
        EventTime1: "9:30 AM",
        Location: "HYDERABAD",
        Status: "Shipment Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "15/06/2025",
        EventTime: "1545",
        EventDate1: "15th June 2025",
        EventTime1: "3:45 PM",
        Location: "HYDERABAD",
        Status: "Shipment Custom Clearance Completed",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "16/06/2025",
        EventTime: "0730",
        EventDate1: "16th June 2025",
        EventTime1: "7:30 AM",
        Location: "HYDERABAD AIRPORT",
        Status: "Shipment Departed from Origin",
        FlightCode: "LH753",
        FlightName: "Lufthansa",
      },
      {
        EventDate: "17/06/2025",
        EventTime: "1345",
        EventDate1: "17th June 2025",
        EventTime1: "1:45 PM",
        Location: "FRANKFURT, GERMANY",
        Status: "Shipment Arrived at Transit Hub",
        FlightCode: "LH753",
        FlightName: "Lufthansa",
      },
      {
        EventDate: "18/06/2025",
        EventTime: "0915",
        EventDate1: "18th June 2025",
        EventTime1: "9:15 AM",
        Location: "FRANKFURT, GERMANY",
        Status: "Shipment Departed from Transit Hub",
        FlightCode: "AC877",
        FlightName: "Air Canada",
      },
      {
        EventDate: "28/06/2025",
        EventTime: "2210",
        EventDate1: "28th June 2025",
        EventTime1: "10:10 PM",
        Location: "TORONTO, CANADA",
        Status: "Shipment Arrived at Destination Airport",
        FlightCode: "AC877",
        FlightName: "Air Canada",
      },
      {
        EventDate: "30/06/2025",
        EventTime: "0830",
        EventDate1: "30th June 2025",
        EventTime1: "8:30 AM",
        Location: "TORONTO CUSTOMS",
        Status: "Shipment Undergoing Customs Clearance",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "30/06/2025",
        EventTime: "1130",
        EventDate1: "30th June 2025",
        EventTime1: "11:30 AM",
        Location: "TORONTO CUSTOMS",
        Status: "Shipment On Hold – Awaiting Clearance Documents",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
