export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "13/06/2025",
        BookTime: "1846",
        BookingDate1: "13th June 2025",
        Origin: "CHENNAI",
        Destination: "Canada",
      },
    ],
    Events: [
      {
        EventDate: "17/09/2025",
        EventTime: "1100",
        EventDate1: "17th Sept 2025",
        EventTime1: "11:00 AM",
        Location: "KUALA LUMPUR, MALAYSIA",
        Status: "Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "16/09/2025",
        EventTime: "1500",
        EventDate1: "16th Sept 2025",
        EventTime1: "3:00 PM",
        Location: "KUALA LUMPUR, MALAYSIA",
        Status: "Shipment Arrived at Destination Airport",
        FlightCode: "MH183",
        FlightName: "Malaysia Airlines",
      },
      {
        EventDate: "14/09/2025",
        EventTime: "1000",
        EventDate1: "14th Sept 2025",
        EventTime1: "10:00 AM",
        Location: "CHENNAI AIRPORT",
        Status: "Shipment Departed from Origin",
        FlightCode: "MH183",
        FlightName: "Malaysia Airlines",
      },
      {
        EventDate: "13/09/2025",
        EventTime: "1630",
        EventDate1: "13th Sept 2025",
        EventTime1: "4:30 PM",
        Location: "CHENNAI AIRPORT",
        Status: "Shipment Received at Origin Airport",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
