export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "09/06/2025",
        BookTime: "1846",
        BookingDate1: "09th April 2025",
        Origin: "CHENNAI",
        Destination: "United Kingdom",
      },
    ],
    Events: [
      {
        EventDate: "09/06/2025",
        EventTime: "1500",
        EventDate1: "9th June 2025",
        EventTime1: "3:00 PM",
        Location: "Chennai",
        Status: "Custom Clearance Completed",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "09/06/2025",
        EventTime: "1065",
        EventDate1: "9th June 2025",
        EventTime1: "10:45 AM",
        Location: "Chennai",
        Status: "Custom Clearance Initiated",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "06/06/2025",
        EventTime: "0831",
        EventDate1: "6th June 2025",
        EventTime1: "8:31 AM",
        Location: "Chennai",
        Status: "Shipment Received at Origin Facility",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
