export default {
  Response: {
    ResponseCode: "RT01",
    ErrorCode: "0",
    ErrorDisc: "Success",
    Tracking: [
      {
        AWBNo: "CH1014956",
        BookingDate: "31/10/2025",
        BookTime: "1846",
        BookingDate1: "31th Oct 2025",
        Origin: "CHENNAI",
        Destination: "USA",
      },
    ],
    Events: [
      {
        EventDate: "10/11/2025",
        EventTime: "0930",
        EventDate1: "10th November 2025",
        EventTime1: "8:30 AM",
        Location: "USA",
        Status: "Under Customs Clearance (USA)",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "07/11/2025",
        EventTime: "2100",
        EventDate1: "7th November 2025",
        EventTime1: "09:00 PM",
        Location: "Germany",
        Status: "Departed to USA",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "05/11/2025",
        EventTime: "1400",
        EventDate1: "5th November 2025",
        EventTime1: "02:00 PM",
        Location: "Germany",
        Status: "Customs Clearance Completed (Germany)",
        FlightCode: "",
        FlightName: "",
      },
      {
        EventDate: "03/11/2025",
        EventTime: "1000",
        EventDate1: "3rd November 2025",
        EventTime1: "10:00 AM",
        Location: "Chennai",
        Status: "Departed from Chennai - On the way to Destination",
        FlightCode: "",
        FlightName: "",
      },
    ],
    AdditionalData: [],
    Dimensions: [],
    Performa: [],
  },
};
